<script lang="ts" setup>
import {Button} from "@/components/ui/button";
import {Switch} from "@/components/ui/switch";
import {Textarea} from "@/components/ui/textarea";
import {Label} from "@/components/ui/label";
import {Input} from "@/components/ui/input";
import {Select, SelectContent, SelectItem, SelectTrigger, SelectValue} from "@/components/ui/select";
import {
  TagsInput,
  TagsInputInput,
  TagsInputItem,
  TagsInputItemDelete,
  TagsInputItemText
} from '@/components/ui/tags-input'

import {Minus, Plus, RotateCcw} from 'lucide-vue-next'
import {engines} from "../../wailsjs/go/models.ts";
import {onBeforeUpdate, onMounted, ref, watch} from 'vue'
import EngineArg = engines.EngineArg;

interface Props {
  args: engines.EngineArg[],
  lgCols?: string,
  mdCols?: string,
  legend?: string,
  currentEngine: engines.EngineMeta
}

const props = withDefaults(defineProps<Props>(), {
  lgCols: "1",
  mdCols: "1",
  legend: "Engine",
})

const refreshArgs = () => {
  props.args.forEach(arg => {
        if (arg.name === "target-extension") {
          // set default from langauge
          if (props.currentEngine.language === "golang") {
            arg.defaultValue = [".go"]
          } else if (props.currentEngine.language === "powershell") {
            arg.defaultValue = [".ps1"]
          }
        }

        if (arg.type === '[]string' && typeof arg.defaultValue === 'string') {
          arg.value = arg.defaultValue ? [arg.defaultValue] : []
        } else {
          arg.value = arg.defaultValue
        }
      }
  )

}

onBeforeUpdate(() => {
  // block summary panel update when args are modified
  // refreshArgs()
})

onMounted(() => {
  refreshArgs()
})

const showArg = (arg: EngineArg) => {
  return arg.notTargetLanguage !== props.currentEngine.language &&
      (arg.targetLanguage === '' || arg.targetLanguage === props.currentEngine.language)
}

// Validation functions remain the same...
const validateByteArrayInput = (input: string): boolean => {
  const mixedFormatPattern =
      /^(([0-9a-fA-F]{2}|\?\?|\d{2}|0x[0-9a-fA-F]{2}|0x\?\?|\\x[0-9a-fA-F]{2}|\\x\?\?)(\s*)?)+$/i;
  const cleanedInput = input.trim().replace(/\s+/g, ' ');
  return mixedFormatPattern.test(cleanedInput);
}

const validateByteInput = (input: string): boolean => {
  const singleBytePattern =
      /^(?:[a-zA-Z0-9]|0x[0-9a-fA-F]{2}|\\x[0-9a-fA-F]{2}|\?\?)$/;
  return singleBytePattern.test(input);
}

const resetToDefault = (index: number) => {
  if (props.args[index].type === '[]string') {
    props.args[index].value = props.args[index].defaultValue ? [props.args[index].defaultValue] : []
  } else {
    props.args[index].value = props.args[index].defaultValue
  }
}

const adjustIntValue = (index: number, increment: boolean) => {
  const currentValue = parseInt(props.args[index].value) || 0;
  props.args[index].value = String(increment ? currentValue + 1 : currentValue - 1);
}

const validationErrors = ref<{ [key: string]: string }>({})

watch(() => props.args, (args) => {
  args.forEach((arg, _) => {
    if (arg.type === '[]byte') {
      if (arg.value && !validateByteArrayInput(arg.value)) {
        validationErrors.value[arg.name] = 'Invalid input format. Valid byte representations (with or without spaces): 0x1a, \x2B, 3C. Use ?? as a placeholder for a randomly generated byte'
      } else {
        delete validationErrors.value[arg.name]
      }
    } else if (arg.type === 'byte') {
      if (arg.value && !validateByteInput(arg.value)) {
        validationErrors.value[arg.name] = 'Invalid input format. Valid formats: single ASCII character, 0xXX, \\xXX, or ??'
      } else {
        delete validationErrors.value[arg.name]
      }
    }
  })
}, {deep: true})
</script>

<template>
  <form class="grid w-full items-start gap-6" @submit.prevent>
    <fieldset class="grid gap-6 rounded-lg border p-4">
      <legend class="-ml-1 px-1 text-sm font-medium">
        {{ props.legend }}
      </legend>
      <div
          :class="`grid gap-4 grid-cols-1 md:grid-cols-${$props.args.length == 1 ? '1' : mdCols} lg:grid-cols-${$props.args.length == 1 ? '1' : lgCols}`">
        <div
            v-for="(arg, index) in $props.args"
            :key="arg.name"
            class="grid gap-2"
        >
          <Label
              class="font-semibold"
              :for="arg.title"
              v-if="showArg(arg)"
          >
            {{ arg.title }}
            <Button
                @click="resetToDefault(index)"
                :class="[
                  'text-muted-foreground cursor-pointer hover:text-muted-foreground m-0 p-0 px-1 max-h-[24px] relative top-[3px] invisible',
                  arg.value !== arg.defaultValue ? 'visible' : ''
                ]"
                variant="ghost"
            >
              <RotateCcw class="max-h-[16px]"/>
              Reset
            </Button>
          </Label>
          <p
              v-if="showArg(arg)"
              class="text-xs text-muted-foreground -mt-[4px]"
          >
            {{ arg.description }}
          </p>

          <!-- String Array Input (Tags) -->
          <template v-if="showArg(arg) && arg.type === '[]string'">
            <TagsInput v-model="$props.args[index].value">
              <TagsInputItem v-for="item in $props.args[index].value" :key="item" :value="item">
                <TagsInputItemText/>
                <TagsInputItemDelete/>
              </TagsInputItem>
              <TagsInputInput placeholder="Add values with [enter]"/>
            </TagsInput>
          </template>

          <!-- Existing input types -->
          <template v-else-if="showArg(arg) && arg.type === 'select'">
            <Select v-model="$props.args[index].value">
              <SelectTrigger>
                <SelectValue :placeholder="`Select ${arg.title}`"/>
              </SelectTrigger>
              <SelectContent>
                <SelectItem
                    v-for="option in arg.availableOptions"
                    :key="option"
                    :value="option"
                >
                  {{ option }}
                </SelectItem>
              </SelectContent>
            </Select>
          </template>

          <template v-else-if="showArg(arg) && arg.type === 'bool'">
            <Switch
                v-model:checked="$props.args[index].value"
                :id="arg.name"
            />
          </template>

          <template v-else-if="showArg(arg) && arg.type === '[]byte'">
            <Textarea
                v-model="$props.args[index].value"
                :id="arg.name"
                :placeholder="arg.title"
                :class="validationErrors[arg.name] ? 'border-red-500' : ''"
            />
            <p
                v-if="validationErrors[arg.name]"
                class="text-xs text-red-500 -mt-[4px]"
            >
              {{ validationErrors[arg.name] }}
            </p>
          </template>

          <template v-else-if="showArg(arg) && arg.type === 'byte'">
            <Input
                v-model="$props.args[index].value"
                :id="arg.name"
                type="text"
                placeholder="Single ASCII, 0xXX, \xXX, or ??"
                :class="validationErrors[arg.name] ? 'border-red-500' : ''"
                maxlength="4"
            />
            <p
                v-if="validationErrors[arg.name]"
                class="text-xs text-red-500 -mt-[4px]"
            >
              {{ validationErrors[arg.name] }}
            </p>
          </template>

          <template v-else-if="showArg(arg) && arg.type === 'int'">
            <div class="flex w-full max-w-sm items-center space-x-2">
              <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  @click="adjustIntValue(index, false)"
              >
                <Minus class="h-4 w-4"/>
              </Button>
              <Input
                  v-model="$props.args[index].value"
                  :id="arg.name"
                  type="number"
                  :placeholder="arg.title"
                  class="w-full"
              />
              <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  @click="adjustIntValue(index, true)"
              >
                <Plus class="h-4 w-4"/>
              </Button>
            </div>
          </template>

          <template v-else-if="showArg(arg)">
            <Input
                v-model="$props.args[index].value"
                :id="arg.name"
                type="text"
                :placeholder="arg.title"
            />
          </template>
        </div>
      </div>
    </fieldset>
  </form>
</template>